### ISSUE TITLE
[Parameter Editor] Both parameter values and parameter overrides are shows with no clear distinction

### ISSUE THREAD

**Issue by LorenzoBichisao-ESA** [STARIONGROUP/COMET-WEB-Community-Edition#430]
In the parameter editor, parameter values and parameter overrides are displayed with no difference. One can only tell the difference by looking at the model code but there should be a cleared indication

**Comment by samatrhea** [comment]
@LorenzoBichisao-ESA would you like to use the same icons as the desktop app or a textual clue?
