### ISSUE TITLE
[Parameter Editor] It would be nice to be able to change parameter values in "sudo-batch-style"

### ISSUE THREAD

**Issue by LorenzoBichisao-ESA** [STARIONGROUP/COMET-WEB-Community-Edition#436]
It would be nice if there was the possibility to change multiple parameter values in one go

**Comment by samatrhea** [comment]
@LorenzoBichisao-ESA , can you please provide a description of how you expect this to work?

**Comment by LorenzoBichisao-ESA** [comment]
Some parameters, such as the power duty cycle, often get set in batch and the values are known all at once. The power duty cycle is made state dependent and can sometimes have as many as 20 states. So often we change each value one by one for each mode, in each state, for all equipment (could be hundreds of equipment). Therefore, it would be really useful to be able to select a large number of parameters and set the value for all selected parameters to a single value.

We have not tried the latest version of the Web App, so in terms of the interface I don't know where the best place for this capability would be. I imagine in the Parameter Editor page where the user usually changes parameter values.
