### ISSUE TITLE
2 tabs of same view: Filtering is identical

### ISSUE THREAD

**Issue by antoineatstariongroup** [STARIONGROUP/COMET-WEB-Community-Edition#689]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When having a view where we can filter, if one tab apply a filter, the second tab automatically have the same filtering.

May be due to the Update of URL implemented on the bodies (tested with the ParameterEditor)

### Logs

  - [ ] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-WEB: 
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version:

**Comment by nathanatstariongroup** [comment]
I had a different behavior, using two model tabs the filtering persisted on 1st tab and the 2nd it kept on reseting when switching between the two model tabs
