### ISSUE TITLE
'Engineering Model' View - 'Add item' button

### ISSUE THREAD

**Issue by ToanAtStarionGroup** [STARIONGROUP/COMET-WEB-Community-Edition#692]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Feature request: A button 'Add Item' in the DataGrid and not in the View Panel. That way, it is always accessible and not hidden behind the data.

### Logs

  - [ ] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-WEB: 
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version:

**Comment by samatstariongroup** [comment]
we decided to not do it in the grid, but in the panel, it was more pleasing to the eye. I close this ticket
