### ISSUE TITLE
allow the user to open the same model-iteration-domain as many times as they see fit

### ISSUE THREAD

**Issue by samatstariongroup** [STARIONGROUP/COMET-WEB-Community-Edition#703]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
allow the user to open the same model-iteration-domain as many times as they see fit

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration

- COMET version:
  - [x] COMET-WEB: 5.2.1

**Comment by joao4all** [comment]
I think this is already allowed. In the screenshot below you can see the same model (iteration and DoE) opened in three different tabs. If that's the case, we can close this issue.

![image](https://github.com/user-attachments/assets/ccc3b9a1-e8a7-4f77-ba70-6f48f32f883d)
