### ISSUE TITLE
When a model does not have a top element, the model dashboard does not load and the application crashes

### ISSUE THREAD

**Issue by samatstariongroup** [STARIONGROUP/COMET-WEB-Community-Edition#719]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a model does not have a top element, the model dashboard does not load and the application crashes

### Steps to Reproduce
open a model that does not have a topelement and notice that the dashboard page does not load and the application throws an error.

### System Configuration

- COMET version:
  - [x] COMET-WEB: 5.5.0
- Web Services:
  - [x] COMET Web Services version: 8.0.2

**Comment by lxatstariongroup** [comment]
Would not surprise me if this CDP4-COMET SDK change solved the issue:

![Image](https://github.com/user-attachments/assets/d19c3f2a-d5c6-4cb8-8915-4fe7d79e7271)
