### ISSUE TITLE
As a user I want to have see ParameterGroups on all Parameter Tables 

### ISSUE THREAD

**Issue by stepjah** [STARIONGROUP/COMET-WEB-Community-Edition#720]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

With a bigger number of parameters the parameter tables need some structure in order to quickly find the right parameter(s). It is recommended to include/display the ParameterGroups (consistent to the IME) for this grouping. This could be either by nesting the parameters in collapsable folders OR just add another column with the owning Parametergroup that would at least allow for sorting and filtering, which ever is more suitable from a GUI layout perspective.

### Logs

  - [x] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-WEB: 4.7.1.0
  - [ ] Other: 
- Web Services:
  - [x] COMET Web Services version: 7.2.0.0

**Comment by samatstariongroup** [comment]
please implement the extra column

**Comment by lxatstariongroup** [comment]
@stepjah I have implemented a new column in the ParameterEditor that shows the complete ParameterGroup path. Will be available in the next release.

**Comment by samatstariongroup** [comment]
@stepjah fixed in version 5.6.0 which is deployed at https://comet-web.cdp4.org
